GET http://127.0.0.1:3000/api/producto?page=1&limit=10&q=

### guardar
POST http://127.0.0.1:3000/api/producto
Content-Type: application/json

{
    "nombre": "PARLANTES",
    "precio": 100,
    "stock": 7,
    "descripcion": "Parlantes DELL",
    "categoriaId": 1
}

### guardar
PUT http://127.0.0.1:3000/api/producto/1
Content-Type: application/json

{
    "nombre": "Monitor modificado",
    "precio": 1200,
    "stock": 6,
    "descripcion": "monitor DELL modificado",
    "categoriaId": 1
}

